name: Hello World

on:
    workflow_dispatch: 

jobs:
    hello-job:
        name: hello-job
        runs-on: ubuntu-latest

        steps:
            - name: Echo text
              run: echo "Hello World"
